=== MiguelAlvarezHernandez/sew/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud, anchura, fecha, hora, vueltas, localidad,
pais, referencias, galeriaDeFotos, galeriaDeVideos, coordenadas, tramos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT galeriaDeFotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT galeriaDeVideos (video+)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT coordenadas (#PCDATA)>
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadasFinales, sector)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT coordenadasFinales (#PCDATA)>
<!ELEMENT sector (#PCDATA)>

<!ATTLIST longitud unidad CDATA #REQUIRED>
<!ATTLIST anchura unidad CDATA #REQUIRED>
<!ATTLIST distancia unidad CDATA #REQUIRED>
<!ATTLIST coordenadas
	longitud CDATA #REQUIRED
	latitud CDATA #REQUIRED
	altitud CDATA #REQUIRED>
<!ATTLIST coordenadasFinales 
	longitud CDATA #REQUIRED
	latitud CDATA #REQUIRED
	altitud CDATA #REQUIRED>

=== MiguelAlvarezHernandez/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>    
<nombre>Barhein</nombre>
<longitud unidad ="km">5.412</longitud> 
<anchura unidad = "m">15</anchura>
<fecha>02-03-1024</fecha>
<hora>16:00</hora>
<vueltas>57</vueltas>
<localidad>Sakhir</localidad>
<pais>Barh√©in</pais>
<referencias>
    <referencia>https://www.formula1.com/en/racing/2024/bahrain</referencia>
    <referencia>https://es.wikipedia.org/wiki/Gran_Premio_de_Bar%C3%A9in</referencia>
    <referencia>https://www.motorsport.com/f1/news/bahrain-grand-prix-guide/</referencia>
</referencias>
<galeriaDeFotos>
    <foto>barheinNight.png</foto>
    <foto>barheinSalida.png</foto>
</galeriaDeFotos>
<galeriaDeVideos>
    <video>pole2024.mp4</video>
</galeriaDeVideos>
<coordenadas longitud = "50.5122" latitud = "26.0335" altitud = "0.0"/>
<tramos>
    <tramo>
        <distancia unidad = "m">650</distancia>
        <coordenadasFinales longitud = "50.5107" latitud = "26.0369" altitud = "0.0"/>
        <sector>1</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">100</distancia>
        <coordenadasFinales longitud = "50.5115" latitud = "26.0363" altitud = "0.0"/>
        <sector>1</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">120</distancia>
        <coordenadasFinales longitud = "50.5125" latitud = "26.0366" altitud = "0.0"/>
        <sector>1</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">600</distancia>
        <coordenadasFinales longitud = "50.5183" latitud = "26.0356" altitud = "0.0"/>
        <sector>1</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">250</distancia>
        <coordenadasFinales longitud = "50.5166" latitud = "26.0339" altitud = "0.0"/>
        <sector>1</sector>
    </tramo>

    <tramo>
        <distancia unidad = "m">100</distancia>
        <coordenadasFinales longitud = "50.5160" latitud = "26.0331" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">100</distancia>
        <coordenadasFinales longitud = "50.5148" latitud = "26.0331" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">250</distancia>
        <coordenadasFinales longitud = "50.5131" latitud = "26.0314" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">350</distancia>
        <coordenadasFinales longitud = "50.5135" latitud = "26.0346" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">100</distancia>
        <coordenadasFinales longitud = "50.5127" latitud = "26.0353" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">700</distancia>
        <coordenadasFinales longitud = "50.5122" latitud = "26.0290" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">60</distancia>
        <coordenadasFinales longitud = "50.5128" latitud = "26.0287" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">90</distancia>
        <coordenadasFinales longitud = "50.5137" latitud = "26.0290" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">200</distancia>
        <coordenadasFinales longitud = "50.5150" latitud = "26.0307" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">200</distancia>
        <coordenadasFinales longitud = "50.5175" latitud = "26.0296" altitud = "0.0"/>
        <sector>2</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">750</distancia>
        <coordenadasFinales longitud = "50.5106" latitud = "26.0260" altitud = "0.0"/>
        <sector>3</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">100</distancia>
        <coordenadasFinales longitud = "50.5102" latitud = "26.0267" altitud = "0.0"/>
        <sector>3</sector>
    </tramo>
    <tramo>
        <distancia unidad = "m">450</distancia>
        <coordenadasFinales longitud = "50.5104" latitud = "26.0310" altitud = "0.0"/>
        <sector>3</sector>
    </tramo>

</tramos>
</circuito>
